### PR TITLE
Makes music page

### PR DESCRIPTION
**Pull request by Unesdala**
Makes the music page look like collegelutheran.org

### CODE REVIEW

**Comment by Unesdala** [comment]
@JoshuaVSherman The .3% difference is from files that were deleted that are no longer applicable. Can't remember if there's a specific command to merge to show conflicts that should be showing up. git merge is showing they're both up to date, despite the changes.

**Comment by JoshuaVSherman** [comment]
@Unesdala no please add this https://www.collegelutheran.org/music

not the josh and maria music :(

**Comment by Unesdala** [comment]
@JoshuaVSherman - It is that one. Dev still has the josh and maria one, though, from the original build. This replaces that, but circleCI is complaining because the pages related to that were deleted.

I know merging into dev will fix that, but thought there was a means of solving the conflict prior to that.

**Comment by JoshuaVSherman** [comment]
@Unesdala sorry, you are correct, please do one thing for me
delete this line from package.json and the comma before this line

    "prepare": "yarn run snyk-protect"

**Comment by JoshuaVSherman** [comment]
@Unesdala super annoying to keep waiting for this ... | Analyzing yarn dependencies for CollegeLutheran project dir

**Pull request merged**
