### PR TITLE
WIP Family page update

### PR DESCRIPTION
**Pull request by Unesdala**

### CODE REVIEW

**Comment by JoshuaVSherman** [comment]
@Unesdala what is the status of this merge please? Are you stuck on something?

**Comment by Unesdala** [comment]
@JoshuaVSherman  Yeah, I'm pulling the data in just fine with redux, and can display it by targeting each one with its index, but I'm having issues getting it to pass along to pic-slider. It's displaying as undefined, instead of mapping through.

**Comment by JoshuaVSherman** [comment]
@Unesdala it should be exactly the same as web-jam.com/music page where the pic slider gets populated, so not sure why it would not be working the same way?

**Comment by JoshuaVSherman** [comment]
@Unesdala ping me on hangouts if you want me to pull down this branch and try to figure it out for you

**Pull request merged**
