### PR TITLE
113 menuitemunittest

### PR DESCRIPTION
**Pull request by kathleenahall**

### CODE REVIEW

**Comment by JoshuaVSherman** [comment]
@kathleenahall you need to finish the rest of the tests for the menuItem.tsx file (you only wrote one test for sortBulletins so far), thanks

**Review by JoshuaVSherman — CHANGES_REQUESTED** [review]
missing tests

**Comment by kathleenahall** [comment]
I was staring at this next one for 3 hours yesterday and got nowhere. I
don't know where to start with a nested conditional, could you help me
start this one?[image: image.png]

**Comment by kathleenahall** [comment]
My best guess to start is (!bulletin || !bulletin[0]) should return link
(bulletin[0])

**Comment by kathleenahall** [comment]
it('sets link to first bulletin listed', () => {
let b: any;
const item = {
classname: '', type: 'link', iconClass: '', link: '', name: '',
};
const results = setBulletin(item, b);
expect().toBe();
});

**Comment by JoshuaVSherman** [comment]
@kathleenahall i am available tomorrow (Tuesday after work to help you)

**Comment by kathleenahall** [comment]
I will be there

**Pull request merged**
